version: '3'
services:
  webapp:
    image: registry.correios.com.br:5043/correios_apache2_php73fpmwsc
    environment:
      - AMBIENTE_PUBLICACAO=D
      - TZ=America/Sao_Paulo
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - .:/opt/sistemas
    links:
      - redis-server
  redis-server:
    image: registry.correios.com.br:5043/redis:latest
    environment:
      - REDIS_PASSWORD=07ad4db6946aede7bb7cbd94fdff7e0d
    ports:
      - 6379:6379
    restart: unless-stopped
